server:
  port: 8086
spring:
  application:
    name: "LoanApplication"
  devtools:
    add-properties: false
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://postgres-loan:5432/loan_application_db}
    username: ${SPRING_R2DBC_USERNAME:root}
    password: ${SPRING_R2DBC_PASSWORD:password}
  sql:
    init:
      mode: "always"
    data:
      r2dbc:
        repositories:
          enabled: true
adapters:
  r2dbc:
    host: postgres-loan
    port: 5432
    database: loan_application_db
    schema: public
    username: root
    password: password
services:
  authentication:
    url: "http://localhost:8085"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

jwt:
  secret: "mysuperlongsecretkeythatismorethan32bytes123!"

adapter:
  restconsumer:
    timeout: 5000
    url: "http://localhost:8085"

resilience4j:
  circuitbreaker:
    instances:
      testGet:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
      testPost:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
